# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 037afeb6c51ddb4af86c456d0c2edeff00f37f807085d04fb0e6ea786130fe9608b0ccb5d82e8a4aa9f7b7c8652e5eb934df956a7ad060affcd518c684b18606

test:
  secret_key_base: 6bf2514eda35c930e694bfb7e7811125742cf2175a0d621052e7689f8d33c1eeb70424ec308da57662b4957f820e8e86b833152dd75f4b073480d2f463d7bad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
